homepage:
    path:     /
    defaults: { controller: 'HomeController::indexAction' }

foo_route:
    path:     /foo
    defaults: { controller: 'FooController::indexAction' }

foo_placeholder_route:
    path:     /foo/{id}
    defaults: { controller: 'FooController::loadAction' }
    requirements:
        id: '[0-9]+'

bar_route:
    path:     /bar
    defaults: { controller: 'BarController::indexAction' }
